---
title: "Analysis of factive verbs"
author: "mcmoyer"
date: "October 22, 2020"
output: html_document
---
  
## Step 1: select stimuli for experiment
  
Set your path here and load some packages that are necessary for visualization 
(ggplot), tidy data handling (tidyr and dplyr), and mixed effects modeling (lme4:
                                                                                                                                                               
```{r}  
setwd("/Users/morganmoyer/Dropbox/Stanford/whquestions-tgrep2/analysis/")
source("/Users/morganmoyer/Dropbox/Stanford/whquestions-tgrep2/analysis/helpers.R")
library(ggplot2)
library(tidyr)
library(dplyr)
library(lme4)
# theme_set(theme_bw())
```

Read the database into R and explore it.
```{r}
d = read.table("/Users/morganmoyer/Dropbox/Stanford/whquestions-tgrep2/corpus/results/swbd.tab",sep="\t",header=T,quote="")
nrow(d) # 10667.....10278....10192 (added MACRO (@WH > /^WH/)...10199 (@WH >> /^WH)
head(d)
str(d)
summary(d)

View(d[1:26])
ncol(d)
names = colnames(d)

for(n in names) {
   d[n] <- as.factor(d$n)
    }
summary(d)

# d = as.factor(d[1:26])
str(d)
table(d$ModalPresent)
```

Take a random sample of 200.
```{r}
s <- sample_n(d, 200)
View(s)
nrow(s)
# write to CSV
write.csv(s, "whq_sample_200.csv",row.names = TRUE)

```
Reproduce the same set
```{r}
# the original DF i sent jd
sa <- read.csv("whq_sample_200_A.csv", header=TRUE)


dnew = semi_join(d, sa, by = c("Item_ID"))
nrow(dnew)


sa = sa[order(sa$Item_ID),]

ddnew = semi_join(sa, d, by=c("Item_ID"))
write.csv(ddnew, "whq_sample_200_neworig.csv",row.names = TRUE)

# try to check if they're the same IDs

ddnew_names = ddnew$Item_ID
sa_names = sa$Item_ID
length(sa_names)

all.equal(ddnew_names,sa_names)

View(ddnew)


snew = d %>%
  filter(Item_ID %in% sa$Item_ID)

write.csv(snew, "whq_sample_200_neworig.csv",row.names = TRUE)
# save it to a csv file and provide an annotation guide for what 
# the different types of features should be
# overleaf. 
# 
```
# some embedded cases aren't printing a matrix verb
```{r}
emb <- subset(d, d$QuestionType=="embedded")
enmv = emb %>%
  filter(MatVerb %in% c(""))
nrow(enmv) # 3333.....0! fixed
View(enmv)

```



```{r}
no_qt = subset(d, d$QuestionType=="")
nrow(no_qt) # 1016....819....20....18...0!
View(no_qt)

mod = subset(d, d$ModalPresent=="yes")
nrow(mod) # 895

nmod = subset(d, d$ModalPresent=="no")
nrow(nmod) # 9235

table(d$ModalPresent)

nf2 <- subset(d, d$Finite=="no") # YES THESE ARE ALL GOOD
nrow(nf2) #190....186?
View(nf2)
# sanity check
nf <- subset(d, d$Finite!="yes") 
nrow(nf) #186
View(nf)

# Do these return all the same ?
all.equal(nf,nf2) # TRUE
````




````{r}
notmod = subset(d, d$ModalPresent!="no" & d$ModalPresent!="yes")
nrow(notmod)
View(notmod)
str(d)
notmodcomp = d %>%
  filter(!ModalPresent %in% c("yes","no")) %>%
  filter(WhPhraseType %in% c("complex"))

notmodcomp2 = subset(notmod, notmod$WhPhaseType=="complex")
nrow(notmodcomp2) # so there are non-complex wh that are failing
notmodnotcomp = subset(notmod, notmod$WhPhaseType!="complex")
nrow(notmodnotcomp)
View(notmodnotcomp)

```


```{r}
dd = grepl("can|could|may|might|must|shall|should", d$Sentence)
View(dd)

mods <- ""
for (r in notmod){
    if (grepl("can|could|may|might|must|shall|should", notmod$Sentence))
    mods + r
  }
```

Graphssss

```{r}
ftable(d$QuestionType,d$ModalPresent)

agr = d %>%
  group_by(QuestionType,ModalPresent,Finite) %>%
  mutate(count = count(Sentence), prop_modal= ) %>%
  
  ggplot(d, aes(x=as.factor(QuestionType),y=as.factor(Finite), fill = as.factor(ModalPresent))) +
  geom_bar()
  
View(agr)

```


